services:
  - type: web
    name: telegram-parser-bot
    env: python
    runtime: python-3.11.9
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p chats channels temp_downloads
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: MY_CHANNEL_ID
        sync: false