services:
  - type: web
    name: telegram-parser-bot
    env: python
    plan: free
    startCommand: python app.py
    buildCommand: pip install -r requirements.txt
    healthCheckPath: /health
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false